# Generated by Django 4.2.7 on 2023-12-11 19:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myForum', '0005_alter_author_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profilePic',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[50, 80], upload_to='media/authors'),
        ),
    ]
