# Generated by Django 4.2.7 on 2023-12-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForum', '0006_category_description_alter_author_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='descripcion'),
        ),
    ]
