# Generated by Django 4.2.6 on 2023-11-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tasa_Eco_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('achs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('museg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('men', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('women', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Mutualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual', models.CharField(max_length=255)),
                ('anio2018', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2019', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2020', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2021', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2022', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('achs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('museg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
