# Generated by Django 4.2.6 on 2023-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidenteLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=255)),
                ('actividad_economica', models.CharField(max_length=255)),
                ('genero_empleado', models.CharField(max_length=10)),
                ('comuna', models.CharField(max_length=255)),
                ('fecha_accidente', models.DateField()),
                ('hora_accidente', models.TimeField()),
                ('descripcion_accidente', models.TextField()),
                ('tipo_accidente', models.CharField(choices=[('Trabajo', 'Accidente de Trabajo'), ('Trayecto', 'Accidente de Trayecto')], max_length=50)),
            ],
        ),
    ]
