# Generated by Django 4.2.6 on 2023-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accidentelaboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentelaboral',
            name='genero_empleado',
        ),
        migrations.AddField(
            model_name='accidentelaboral',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accidentelaboral',
            name='tipo_accidente',
            field=models.CharField(choices=[('trabajo', 'Trabajo'), ('trayecto', 'Trayecto')], max_length=50),
        ),
    ]
