# Generated by Django 4.2.6 on 2023-12-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_accidentelaboral_genero_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tasa_Eco_Act',
            new_name='TasaxAct',
        ),
        migrations.RenameField(
            model_name='economicactivity',
            old_name='name',
            new_name='activity_name',
        ),
        migrations.RenameField(
            model_name='mutualidad',
            old_name='mutual',
            new_name='mutualidad_name',
        ),
        migrations.RenameField(
            model_name='sexo',
            old_name='name',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='economicactivity',
            name='achs',
        ),
        migrations.RemoveField(
            model_name='economicactivity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='economicactivity',
            name='ist',
        ),
        migrations.RemoveField(
            model_name='economicactivity',
            name='museg',
        ),
        migrations.RemoveField(
            model_name='economicactivity',
            name='total',
        ),
        migrations.RemoveField(
            model_name='mutualidad',
            name='anio2018',
        ),
        migrations.RemoveField(
            model_name='mutualidad',
            name='anio2019',
        ),
        migrations.RemoveField(
            model_name='mutualidad',
            name='anio2020',
        ),
        migrations.RemoveField(
            model_name='mutualidad',
            name='anio2021',
        ),
        migrations.RemoveField(
            model_name='mutualidad',
            name='anio2022',
        ),
        migrations.RemoveField(
            model_name='mutualidad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='men',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='women',
        ),
        migrations.CreateModel(
            name='ExcelPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excelfile')),
            ],
        ),
        migrations.CreateModel(
            name='DiasxMut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutual', models.CharField(max_length=255)),
                ('anio2018', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2019', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2020', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2021', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('anio2022', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='DiasxActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('museg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EconomicActivity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.economicactivity')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('mutualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mutualidad')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentesxSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('men', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('women', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
