# Generated by Django 4.2.6 on 2023-10-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_economicactivity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicactivity',
            name='achs',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='economicactivity',
            name='ist',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='economicactivity',
            name='museg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
