# Generated by Django 4.2.6 on 2023-12-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_excelfile_rename_tasa_eco_act_tasaxact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasxactividad',
            name='mutualidad',
        ),
    ]
