# Generated by Django 4.2.6 on 2023-12-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_diasxactividad_mutualidad'),
    ]

    operations = [
    ]
