# Generated by Django 4.2.6 on 2023-12-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231209_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentesxsexo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tasaxact',
            name='name',
        ),
        migrations.AddField(
            model_name='accidentesxsexo',
            name='EconomicActivity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.economicactivity'),
        ),
        migrations.AddField(
            model_name='tasaxact',
            name='EconomicActivity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.economicactivity'),
        ),
        migrations.AlterField(
            model_name='accidentelaboral',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accidentelaboral',
            name='tipo_accidente',
            field=models.CharField(choices=[('Trabajo', 'Trabajo'), ('Trayecto', 'Trayecto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='diasxmut',
            name='mutual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.mutualidad'),
        ),
    ]
