# Generated by Django 4.2.6 on 2023-12-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_region_accidentesxregion_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcelPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.excelfile')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='fallecidosxact',
            name='EconomicActivity',
        ),
        migrations.RemoveField(
            model_name='fallecidosxact',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fallecidosxact',
            name='year',
        ),
        migrations.RemoveField(
            model_name='fallecidosxsexo',
            name='EconomicActivity',
        ),
        migrations.RemoveField(
            model_name='fallecidosxsexo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fallecidosxsexo',
            name='year',
        ),
        migrations.RemoveField(
            model_name='porcentajexact',
            name='EconomicActivity',
        ),
        migrations.RemoveField(
            model_name='porcentajexact',
            name='category',
        ),
        migrations.RemoveField(
            model_name='porcentajexact',
            name='year',
        ),
        migrations.RemoveField(
            model_name='accidentesxsexo',
            name='year',
        ),
        migrations.RemoveField(
            model_name='diasxactividad',
            name='year',
        ),
        migrations.RemoveField(
            model_name='diasxmut',
            name='year',
        ),
        migrations.RemoveField(
            model_name='tasaxact',
            name='year',
        ),
        migrations.DeleteModel(
            name='AccidentesxRegion',
        ),
        migrations.DeleteModel(
            name='FallecidosxAct',
        ),
        migrations.DeleteModel(
            name='FallecidosxSexo',
        ),
        migrations.DeleteModel(
            name='PorcentajexAct',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
