# Generated by Django 4.2.6 on 2023-12-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_excelfile_excelpage_sexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentesxRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('museg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='FallecidosxAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('museg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('isl', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EconomicActivity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.economicactivity')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='FallecidosxSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('women', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EconomicActivity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.economicactivity')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='PorcentajexAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('museg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ist', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EconomicActivity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.economicactivity')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='excelpage',
            name='file',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='ExcelFile',
        ),
        migrations.DeleteModel(
            name='ExcelPage',
        ),
        migrations.AddField(
            model_name='porcentajexact',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='fallecidosxsexo',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='fallecidosxact',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='accidentesxregion',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddField(
            model_name='accidentesxregion',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='accidentesxsexo',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='diasxactividad',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='diasxmut',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AddField(
            model_name='tasaxact',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
    ]
