# Generated by Django 4.2.6 on 2023-12-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_accidentesxregion_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesxregion',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
    ]
