# Generated by Django 4.2.6 on 2023-12-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_accidentesxsexo_year_alter_diasxactividad_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesxregion',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxact',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxsexo',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
