# Generated by Django 4.2.6 on 2023-12-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_accidentesxregion_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallecidosxact',
            name='achs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxact',
            name='isl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxact',
            name='ist',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxact',
            name='museg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxact',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxsexo',
            name='men',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxsexo',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fallecidosxsexo',
            name='women',
            field=models.IntegerField(null=True),
        ),
    ]
