# Generated by Django 4.2.6 on 2023-12-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_fallecidosxact_achs_alter_fallecidosxact_isl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasxactividad',
            name='cchc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tasaxact',
            name='cchc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
