# Generated by Django 4.2.6 on 2023-12-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_diasxactividad_cchc_tasaxact_cchc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesxregion',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
