# Generated by Django 4.2.6 on 2023-12-11 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_accidentesxregion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentesxregion',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
