# Generated by Django 4.2.6 on 2023-12-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_accidentesxregion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
