# Generated by Django 4.2.6 on 2023-12-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_accidentesxregion_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentelaboral',
            name='comuna',
        ),
        migrations.AddField(
            model_name='accidentelaboral',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AlterField(
            model_name='accidentelaboral',
            name='tipo_accidente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
